### ISSUE TITLE
Can you explain how to use DCA-PLDA with embedding extracted with Kaldi?

### ISSUE THREAD

**Issue by speakershn** [luferrer/DCA-PLDA#3]
The format is not hdf5 or npz using kaldi so I am not sure what to change in the code.

Thank you very much!

**Comment by luferrer** [comment]
Hi, for now we do not have a loader for Kaldi format, but you can transform the embeddings from Kaldi to any of the two formats above as a pre-processing step. You can download the data linked from the readme file to see an example of what the hdf5 format should look like. Alternatively, you can just save a dictionary with the list of ids and the data (with keys 'ids' and 'data', respectively) in npz format. 

I hope that helps.

Luciana
