### ISSUE TITLE
Question when using compute_performance_with_confidence_intervals

### ISSUE THREAD

**Issue by JaesungHuh** [luferrer/DCA-PLDA#9]
Hi, i think there is a bug in the code below.
https://github.com/luferrer/DCA-PLDA/blob/e47aff3c336128942e866ece81838d4ec99d7237/dca_plda/scores.py#L484

The original code is :
```
sel_key = Key(np.array(key.test_ids)[sel_test_idxs], np.array(key.enroll_ids)[sel_enroll_idxs], key.mask[np.ix_(sel_enroll_idxs,sel_test_idxs)]) 
```

but according to the __init__ function of Key, I think it should be :
```
sel_key = Key(np.array(key.enroll_ids)[sel_enroll_idxs], np.array(key.test_ids)[sel_test_idxs], key.mask[np.ix_(sel_enroll_idxs,sel_test_idxs)]) 
```

Please let me know if I'm wrong.

Thank you.

Best wishes,
Jaesung

**Comment by luferrer** [comment]
You are completely right. I have pushed the fix. Thanks for letting me know.
